services:
  db:
    ports:
      - "54325:5432"
    volumes:
      - "${HOST_DB_DATA_PATH:-/home/muad/fifoteca/data/postgres}:/var/lib/postgresql/data/pgdata"

  prestart:
    networks:
      - default

  backend:
    networks:
      - default
    ports:
      - "${HOST_BACKEND_PORT:-18437}:8000"

  frontend:
    networks:
      - default
    ports:
      - "${HOST_FRONTEND_PORT:-53172}:80"
    build:
      args:
        - VITE_API_URL=${VITE_API_URL?Variable not set}
        - NODE_ENV=production

  # Keep Adminer off by default in deployed environments.
  adminer:
    networks:
      - default
    profiles:
      - tools
