// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const FifaLeaguePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        country: {
            type: 'string',
            title: 'Country'
        }
    },
    type: 'object',
    required: ['id', 'name', 'country'],
    title: 'FifaLeaguePublic'
} as const;

export const FifaTeamPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        league_id: {
            type: 'string',
            format: 'uuid',
            title: 'League Id'
        },
        attack_rating: {
            type: 'integer',
            title: 'Attack Rating'
        },
        midfield_rating: {
            type: 'integer',
            title: 'Midfield Rating'
        },
        defense_rating: {
            type: 'integer',
            title: 'Defense Rating'
        },
        overall_rating: {
            type: 'integer',
            title: 'Overall Rating'
        }
    },
    type: 'object',
    required: ['id', 'name', 'league_id', 'attack_rating', 'midfield_rating', 'defense_rating', 'overall_rating'],
    title: 'FifaTeamPublic'
} as const;

export const FifotecaMatchDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        room_id: {
            type: 'string',
            format: 'uuid',
            title: 'Room Id'
        },
        round_number: {
            type: 'integer',
            title: 'Round Number'
        },
        player1_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player1 Id'
        },
        player2_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player2 Id'
        },
        player1_team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player1 Team Id'
        },
        player2_team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player2 Team Id'
        },
        player1_league_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player1 League Id'
        },
        player2_league_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player2 League Id'
        },
        player1_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player1 Score'
        },
        player2_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player2 Score'
        },
        rating_difference: {
            type: 'integer',
            title: 'Rating Difference'
        },
        protection_awarded_to_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Protection Awarded To Id'
        },
        submitted_by_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Submitted By Id'
        },
        confirmed: {
            type: 'boolean',
            title: 'Confirmed'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'room_id', 'round_number', 'player1_id', 'player2_id', 'player1_team_id', 'player2_team_id', 'player1_league_id', 'player2_league_id', 'player1_score', 'player2_score', 'rating_difference', 'protection_awarded_to_id', 'submitted_by_id', 'confirmed', 'created_at'],
    title: 'FifotecaMatchDetail',
    description: 'Detailed match schema (with team and submitter info).'
} as const;

export const FifotecaMatchHistoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        round_number: {
            type: 'integer',
            title: 'Round Number'
        },
        rating_difference: {
            type: 'integer',
            title: 'Rating Difference'
        },
        confirmed: {
            type: 'boolean',
            title: 'Confirmed'
        },
        opponent_display_name: {
            type: 'string',
            title: 'Opponent Display Name'
        },
        my_team_name: {
            type: 'string',
            title: 'My Team Name'
        },
        opponent_team_name: {
            type: 'string',
            title: 'Opponent Team Name'
        },
        my_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'My Score'
        },
        opponent_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opponent Score'
        },
        result: {
            type: 'string',
            title: 'Result'
        }
    },
    type: 'object',
    required: ['id', 'created_at', 'round_number', 'rating_difference', 'confirmed', 'opponent_display_name', 'my_team_name', 'opponent_team_name', 'my_score', 'opponent_score', 'result'],
    title: 'FifotecaMatchHistoryPublic',
    description: "Enriched match history from current player's perspective."
} as const;

export const FifotecaMatchPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        room_id: {
            type: 'string',
            format: 'uuid',
            title: 'Room Id'
        },
        round_number: {
            type: 'integer',
            title: 'Round Number'
        },
        player1_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player1 Id'
        },
        player2_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player2 Id'
        },
        player1_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player1 Score'
        },
        player2_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player2 Score'
        },
        rating_difference: {
            type: 'integer',
            title: 'Rating Difference'
        },
        protection_awarded_to_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Protection Awarded To Id'
        },
        confirmed: {
            type: 'boolean',
            title: 'Confirmed'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'room_id', 'round_number', 'player1_id', 'player2_id', 'player1_score', 'player2_score', 'rating_difference', 'protection_awarded_to_id', 'confirmed', 'created_at'],
    title: 'FifotecaMatchPublic',
    description: 'Public match schema (minimal).'
} as const;

export const FifotecaPlayerPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        total_wins: {
            type: 'integer',
            title: 'Total Wins'
        },
        total_losses: {
            type: 'integer',
            title: 'Total Losses'
        },
        total_draws: {
            type: 'integer',
            title: 'Total Draws'
        },
        has_protection: {
            type: 'boolean',
            title: 'Has Protection'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'display_name', 'total_wins', 'total_losses', 'total_draws', 'has_protection'],
    title: 'FifotecaPlayerPublic'
} as const;

export const FifotecaPlayerStatePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        room_id: {
            type: 'string',
            format: 'uuid',
            title: 'Room Id'
        },
        player_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player Id'
        },
        round_number: {
            type: 'integer',
            title: 'Round Number'
        },
        phase: {
            type: 'string',
            title: 'Phase'
        },
        league_spins_remaining: {
            type: 'integer',
            title: 'League Spins Remaining'
        },
        team_spins_remaining: {
            type: 'integer',
            title: 'Team Spins Remaining'
        },
        current_league_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current League Id'
        },
        current_team_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Team Id'
        },
        league_locked: {
            type: 'boolean',
            title: 'League Locked'
        },
        team_locked: {
            type: 'boolean',
            title: 'Team Locked'
        },
        has_superspin: {
            type: 'boolean',
            title: 'Has Superspin'
        },
        superspin_used: {
            type: 'boolean',
            title: 'Superspin Used'
        },
        has_parity_spin: {
            type: 'boolean',
            title: 'Has Parity Spin'
        },
        parity_spin_used: {
            type: 'boolean',
            title: 'Parity Spin Used'
        }
    },
    type: 'object',
    required: ['id', 'room_id', 'player_id', 'round_number', 'phase', 'league_spins_remaining', 'team_spins_remaining', 'current_league_id', 'current_team_id', 'league_locked', 'team_locked', 'has_superspin', 'superspin_used', 'has_parity_spin', 'parity_spin_used'],
    title: 'FifotecaPlayerStatePublic'
} as const;

export const FifotecaRoomPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        ruleset: {
            type: 'string',
            title: 'Ruleset'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        player1_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player1 Id'
        },
        player2_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player2 Id'
        },
        current_turn_player_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Turn Player Id'
        },
        first_player_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Player Id'
        },
        round_number: {
            type: 'integer',
            title: 'Round Number'
        },
        mutual_superspin_active: {
            type: 'boolean',
            title: 'Mutual Superspin Active'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'code', 'ruleset', 'status', 'player1_id', 'player2_id', 'current_turn_player_id', 'first_player_id', 'round_number', 'mutual_superspin_active', 'expires_at', 'created_at'],
    title: 'FifotecaRoomPublic'
} as const;

export const FifotecaRoomWithStatesPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        ruleset: {
            type: 'string',
            title: 'Ruleset'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        player1_id: {
            type: 'string',
            format: 'uuid',
            title: 'Player1 Id'
        },
        player2_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player2 Id'
        },
        current_turn_player_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Turn Player Id'
        },
        first_player_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Player Id'
        },
        round_number: {
            type: 'integer',
            title: 'Round Number'
        },
        mutual_superspin_active: {
            type: 'boolean',
            title: 'Mutual Superspin Active'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        player_states: {
            items: {
                '$ref': '#/components/schemas/FifotecaPlayerStatePublic'
            },
            type: 'array',
            title: 'Player States'
        }
    },
    type: 'object',
    required: ['id', 'code', 'ruleset', 'status', 'player1_id', 'player2_id', 'current_turn_player_id', 'first_player_id', 'round_number', 'mutual_superspin_active', 'expires_at', 'created_at', 'player_states'],
    title: 'FifotecaRoomWithStatesPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MatchScoreSubmitSchema = {
    properties: {
        player1_score: {
            type: 'integer',
            minimum: 0,
            title: 'Player1 Score'
        },
        player2_score: {
            type: 'integer',
            minimum: 0,
            title: 'Player2 Score'
        }
    },
    type: 'object',
    required: ['player1_score', 'player2_score'],
    title: 'MatchScoreSubmit',
    description: 'Request schema for submitting match scores.'
} as const;

export const MatchesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FifotecaMatchHistoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MatchesPublic',
    description: 'List of matches for current player.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;