// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { FifotecaReadLeaguesResponse, FifotecaReadLeagueTeamsData, FifotecaReadLeagueTeamsResponse, FifotecaSubmitMatchScoreData, FifotecaSubmitMatchScoreResponse, FifotecaConfirmMatchResultData, FifotecaConfirmMatchResultResponse, FifotecaListMatchesResponse, FifotecaGetMatchData, FifotecaGetMatchResponse, FifotecaListPlayersResponse, FifotecaGetPlayerProfileResponse, FifotecaCreateOrGetPlayerProfileResponse, FifotecaCreateRoomData, FifotecaCreateRoomResponse, FifotecaJoinRoomData, FifotecaJoinRoomResponse, FifotecaGetRoomData, FifotecaGetRoomResponse, FifotecaReadTeamsData, FifotecaReadTeamsResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class FifotecaService {
    /**
     * Read Leagues
     * Retrieve all leagues.
     * @returns FifaLeaguePublic Successful Response
     * @throws ApiError
     */
    public static readLeagues(): CancelablePromise<FifotecaReadLeaguesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/leagues/'
        });
    }
    
    /**
     * Read League Teams
     * Retrieve all teams in a specific league.
     * @param data The data for the request.
     * @param data.id
     * @returns FifaTeamPublic Successful Response
     * @throws ApiError
     */
    public static readLeagueTeams(data: FifotecaReadLeagueTeamsData): CancelablePromise<FifotecaReadLeagueTeamsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/leagues/{id}/teams',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Submit Match Score
     * Submit scores for a match.
     *
     * Only participants can submit scores. Scores can only be submitted once
     * while the room is in MATCH_IN_PROGRESS status.
     *
     * Args:
     * id: The match ID.
     * score_data: The scores (player1_score, player2_score).
     * current_user: The authenticated user.
     * session: Database session.
     *
     * Returns:
     * The updated match.
     *
     * Raises:
     * HTTPException: If player not participant (403).
     * HTTPException: If match already confirmed (400).
     * HTTPException: If scores already submitted (400).
     * HTTPException: If room not in MATCH_IN_PROGRESS (400).
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns FifotecaMatchPublic Successful Response
     * @throws ApiError
     */
    public static submitMatchScore(data: FifotecaSubmitMatchScoreData): CancelablePromise<FifotecaSubmitMatchScoreResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/matches/{id}/score',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Confirm Match Result
     * Confirm match result and update player statistics.
     *
     * Only the non-submitting participant can confirm. Confirmation updates
     * player win/loss/draw totals and sets room to COMPLETED.
     *
     * Args:
     * id: The match ID.
     * current_user: The authenticated user.
     * session: Database session.
     *
     * Returns:
     * The confirmed match.
     *
     * Raises:
     * HTTPException: If player not participant (403).
     * HTTPException: If scores not submitted (400).
     * HTTPException: If match already confirmed (400).
     * HTTPException: If submitting player tries to confirm (403).
     * @param data The data for the request.
     * @param data.id
     * @returns FifotecaMatchPublic Successful Response
     * @throws ApiError
     */
    public static confirmMatchResult(data: FifotecaConfirmMatchResultData): CancelablePromise<FifotecaConfirmMatchResultResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/matches/{id}/confirm',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Matches
     * List all matches for the current player.
     *
     * Returns matches where the player is either player1 or player2,
     * sorted by creation date (newest first). Each match includes
     * enriched data from the current player's perspective.
     *
     * Args:
     * current_user: The authenticated user.
     * session: Database session.
     *
     * Returns:
     * List of matches with opponent/team names and result from player's view.
     * @returns MatchesPublic Successful Response
     * @throws ApiError
     */
    public static listMatches(): CancelablePromise<FifotecaListMatchesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/matches'
        });
    }
    
    /**
     * Get Match
     * Get detailed match information.
     *
     * Only participants can view match details.
     *
     * Args:
     * id: The match ID.
     * current_user: The authenticated user.
     * session: Database session.
     *
     * Returns:
     * Detailed match information.
     *
     * Raises:
     * HTTPException: If player not participant (403).
     * HTTPException: If match not found (404).
     * @param data The data for the request.
     * @param data.id
     * @returns FifotecaMatchDetail Successful Response
     * @throws ApiError
     */
    public static getMatch(data: FifotecaGetMatchData): CancelablePromise<FifotecaGetMatchResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/matches/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Players
     * List all registered Fifoteca players.
     * @returns FifotecaPlayerPublic Successful Response
     * @throws ApiError
     */
    public static listPlayers(): CancelablePromise<FifotecaListPlayersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/players'
        });
    }
    
    /**
     * Get Player Profile
     * Get the current user's player profile with stats.
     *
     * Returns 404 if profile does not exist (use POST /me to create).
     * @returns FifotecaPlayerPublic Successful Response
     * @throws ApiError
     */
    public static getPlayerProfile(): CancelablePromise<FifotecaGetPlayerProfileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/players/me'
        });
    }
    
    /**
     * Create Or Get Player Profile
     * Create or get the current user's player profile.
     *
     * If a profile already exists for the current user, returns the existing profile.
     * Otherwise, creates a new profile with default stats (0/0/0).
     *
     * Display name is derived from user.full_name or user.email.
     * @returns FifotecaPlayerPublic Successful Response
     * @throws ApiError
     */
    public static createOrGetPlayerProfile(): CancelablePromise<FifotecaCreateOrGetPlayerProfileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/players/me'
        });
    }
    
    /**
     * Create Room
     * Create a new game room.
     *
     * Generates a unique 6-character room code and initializes the room
     * in WAITING status. Room expires after 60 minutes.
     * @param data The data for the request.
     * @param data.ruleset
     * @returns FifotecaRoomPublic Successful Response
     * @throws ApiError
     */
    public static createRoom(data: FifotecaCreateRoomData = {}): CancelablePromise<FifotecaCreateRoomResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/rooms',
            query: {
                ruleset: data.ruleset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Join Room
     * Join an existing game room.
     *
     * Validates that the room exists, is in WAITING status, is not full,
     * and the player is not trying to join their own room.
     * On successful join, initializes player states for both players.
     * @param data The data for the request.
     * @param data.code
     * @returns FifotecaRoomPublic Successful Response
     * @throws ApiError
     */
    public static joinRoom(data: FifotecaJoinRoomData): CancelablePromise<FifotecaJoinRoomResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/rooms/join/{code}',
            path: {
                code: data.code
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Room
     * Get room state including player states.
     *
     * Used for reconnection and state synchronization.
     * Returns 404 if room doesn't exist, 410 if room has expired.
     * @param data The data for the request.
     * @param data.code
     * @returns FifotecaRoomWithStatesPublic Successful Response
     * @throws ApiError
     */
    public static getRoom(data: FifotecaGetRoomData): CancelablePromise<FifotecaGetRoomResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/rooms/{code}',
            path: {
                code: data.code
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Teams
     * Retrieve teams with optional filtering by league and rating range.
     * @param data The data for the request.
     * @param data.leagueId Filter by league ID
     * @param data.minRating Minimum overall rating
     * @param data.maxRating Maximum overall rating
     * @returns FifaTeamPublic Successful Response
     * @throws ApiError
     */
    public static readTeams(data: FifotecaReadTeamsData = {}): CancelablePromise<FifotecaReadTeamsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/teams/',
            query: {
                league_id: data.leagueId,
                min_rating: data.minRating,
                max_rating: data.maxRating
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LeaguesService {
    /**
     * Read Leagues
     * Retrieve all leagues.
     * @returns FifaLeaguePublic Successful Response
     * @throws ApiError
     */
    public static fifotecaReadLeagues(): CancelablePromise<FifotecaReadLeaguesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/leagues/'
        });
    }
    
    /**
     * Read League Teams
     * Retrieve all teams in a specific league.
     * @param data The data for the request.
     * @param data.id
     * @returns FifaTeamPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaReadLeagueTeams(data: FifotecaReadLeagueTeamsData): CancelablePromise<FifotecaReadLeagueTeamsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/leagues/{id}/teams',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class MatchesService {
    /**
     * Submit Match Score
     * Submit scores for a match.
     *
     * Only participants can submit scores. Scores can only be submitted once
     * while the room is in MATCH_IN_PROGRESS status.
     *
     * Args:
     * id: The match ID.
     * score_data: The scores (player1_score, player2_score).
     * current_user: The authenticated user.
     * session: Database session.
     *
     * Returns:
     * The updated match.
     *
     * Raises:
     * HTTPException: If player not participant (403).
     * HTTPException: If match already confirmed (400).
     * HTTPException: If scores already submitted (400).
     * HTTPException: If room not in MATCH_IN_PROGRESS (400).
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns FifotecaMatchPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaSubmitMatchScore(data: FifotecaSubmitMatchScoreData): CancelablePromise<FifotecaSubmitMatchScoreResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/matches/{id}/score',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Confirm Match Result
     * Confirm match result and update player statistics.
     *
     * Only the non-submitting participant can confirm. Confirmation updates
     * player win/loss/draw totals and sets room to COMPLETED.
     *
     * Args:
     * id: The match ID.
     * current_user: The authenticated user.
     * session: Database session.
     *
     * Returns:
     * The confirmed match.
     *
     * Raises:
     * HTTPException: If player not participant (403).
     * HTTPException: If scores not submitted (400).
     * HTTPException: If match already confirmed (400).
     * HTTPException: If submitting player tries to confirm (403).
     * @param data The data for the request.
     * @param data.id
     * @returns FifotecaMatchPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaConfirmMatchResult(data: FifotecaConfirmMatchResultData): CancelablePromise<FifotecaConfirmMatchResultResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/matches/{id}/confirm',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Matches
     * List all matches for the current player.
     *
     * Returns matches where the player is either player1 or player2,
     * sorted by creation date (newest first). Each match includes
     * enriched data from the current player's perspective.
     *
     * Args:
     * current_user: The authenticated user.
     * session: Database session.
     *
     * Returns:
     * List of matches with opponent/team names and result from player's view.
     * @returns MatchesPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaListMatches(): CancelablePromise<FifotecaListMatchesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/matches'
        });
    }
    
    /**
     * Get Match
     * Get detailed match information.
     *
     * Only participants can view match details.
     *
     * Args:
     * id: The match ID.
     * current_user: The authenticated user.
     * session: Database session.
     *
     * Returns:
     * Detailed match information.
     *
     * Raises:
     * HTTPException: If player not participant (403).
     * HTTPException: If match not found (404).
     * @param data The data for the request.
     * @param data.id
     * @returns FifotecaMatchDetail Successful Response
     * @throws ApiError
     */
    public static fifotecaGetMatch(data: FifotecaGetMatchData): CancelablePromise<FifotecaGetMatchResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/matches/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PlayersService {
    /**
     * List Players
     * List all registered Fifoteca players.
     * @returns FifotecaPlayerPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaListPlayers(): CancelablePromise<FifotecaListPlayersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/players'
        });
    }
    
    /**
     * Get Player Profile
     * Get the current user's player profile with stats.
     *
     * Returns 404 if profile does not exist (use POST /me to create).
     * @returns FifotecaPlayerPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaGetPlayerProfile(): CancelablePromise<FifotecaGetPlayerProfileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/players/me'
        });
    }
    
    /**
     * Create Or Get Player Profile
     * Create or get the current user's player profile.
     *
     * If a profile already exists for the current user, returns the existing profile.
     * Otherwise, creates a new profile with default stats (0/0/0).
     *
     * Display name is derived from user.full_name or user.email.
     * @returns FifotecaPlayerPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaCreateOrGetPlayerProfile(): CancelablePromise<FifotecaCreateOrGetPlayerProfileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/players/me'
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class RoomsService {
    /**
     * Create Room
     * Create a new game room.
     *
     * Generates a unique 6-character room code and initializes the room
     * in WAITING status. Room expires after 60 minutes.
     * @param data The data for the request.
     * @param data.ruleset
     * @returns FifotecaRoomPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaCreateRoom(data: FifotecaCreateRoomData = {}): CancelablePromise<FifotecaCreateRoomResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/rooms',
            query: {
                ruleset: data.ruleset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Join Room
     * Join an existing game room.
     *
     * Validates that the room exists, is in WAITING status, is not full,
     * and the player is not trying to join their own room.
     * On successful join, initializes player states for both players.
     * @param data The data for the request.
     * @param data.code
     * @returns FifotecaRoomPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaJoinRoom(data: FifotecaJoinRoomData): CancelablePromise<FifotecaJoinRoomResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/fifoteca/rooms/join/{code}',
            path: {
                code: data.code
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Room
     * Get room state including player states.
     *
     * Used for reconnection and state synchronization.
     * Returns 404 if room doesn't exist, 410 if room has expired.
     * @param data The data for the request.
     * @param data.code
     * @returns FifotecaRoomWithStatesPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaGetRoom(data: FifotecaGetRoomData): CancelablePromise<FifotecaGetRoomResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/rooms/{code}',
            path: {
                code: data.code
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TeamsService {
    /**
     * Read Teams
     * Retrieve teams with optional filtering by league and rating range.
     * @param data The data for the request.
     * @param data.leagueId Filter by league ID
     * @param data.minRating Minimum overall rating
     * @param data.maxRating Maximum overall rating
     * @returns FifaTeamPublic Successful Response
     * @throws ApiError
     */
    public static fifotecaReadTeams(data: FifotecaReadTeamsData = {}): CancelablePromise<FifotecaReadTeamsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fifoteca/teams/',
            query: {
                league_id: data.leagueId,
                min_rating: data.minRating,
                max_rating: data.maxRating
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}