// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FifaLeaguePublic = {
    id: string;
    name: string;
    country: string;
};

export type FifaTeamPublic = {
    id: string;
    name: string;
    league_id: string;
    attack_rating: number;
    midfield_rating: number;
    defense_rating: number;
    overall_rating: number;
};

/**
 * Detailed match schema (with team and submitter info).
 */
export type FifotecaMatchDetail = {
    id: string;
    room_id: string;
    round_number: number;
    player1_id: string;
    player2_id: string;
    player1_team_id: string;
    player2_team_id: string;
    player1_league_id: string;
    player2_league_id: string;
    player1_score: (number | null);
    player2_score: (number | null);
    rating_difference: number;
    protection_awarded_to_id: (string | null);
    submitted_by_id: (string | null);
    confirmed: boolean;
    created_at: (string | null);
};

/**
 * Enriched match history from current player's perspective.
 */
export type FifotecaMatchHistoryPublic = {
    id: string;
    created_at: (string | null);
    round_number: number;
    rating_difference: number;
    confirmed: boolean;
    opponent_display_name: string;
    my_team_name: string;
    opponent_team_name: string;
    my_score: (number | null);
    opponent_score: (number | null);
    result: string;
};

/**
 * Public match schema (minimal).
 */
export type FifotecaMatchPublic = {
    id: string;
    room_id: string;
    round_number: number;
    player1_id: string;
    player2_id: string;
    player1_score: (number | null);
    player2_score: (number | null);
    rating_difference: number;
    protection_awarded_to_id: (string | null);
    confirmed: boolean;
    created_at: (string | null);
};

export type FifotecaPlayerPublic = {
    id: string;
    user_id: string;
    display_name: string;
    total_wins: number;
    total_losses: number;
    total_draws: number;
    has_protection: boolean;
};

export type FifotecaPlayerStatePublic = {
    id: string;
    room_id: string;
    player_id: string;
    round_number: number;
    phase: string;
    league_spins_remaining: number;
    team_spins_remaining: number;
    current_league_id: (string | null);
    current_team_id: (string | null);
    league_locked: boolean;
    team_locked: boolean;
    has_superspin: boolean;
    superspin_used: boolean;
    has_parity_spin: boolean;
    parity_spin_used: boolean;
};

export type FifotecaRoomPublic = {
    id: string;
    code: string;
    ruleset: string;
    status: string;
    player1_id: string;
    player2_id: (string | null);
    current_turn_player_id: (string | null);
    first_player_id: (string | null);
    round_number: number;
    mutual_superspin_active: boolean;
    expires_at: string;
    created_at: (string | null);
};

export type FifotecaRoomWithStatesPublic = {
    id: string;
    code: string;
    ruleset: string;
    status: string;
    player1_id: string;
    player2_id: (string | null);
    current_turn_player_id: (string | null);
    first_player_id: (string | null);
    round_number: number;
    mutual_superspin_active: boolean;
    expires_at: string;
    created_at: (string | null);
    player_states: Array<FifotecaPlayerStatePublic>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * List of matches for current player.
 */
export type MatchesPublic = {
    data: Array<FifotecaMatchHistoryPublic>;
    count: number;
};

/**
 * Request schema for submitting match scores.
 */
export type MatchScoreSubmit = {
    player1_score: number;
    player2_score: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type FifotecaReadLeaguesResponse = (Array<FifaLeaguePublic>);

export type FifotecaReadLeagueTeamsData = {
    id: string;
};

export type FifotecaReadLeagueTeamsResponse = (Array<FifaTeamPublic>);

export type FifotecaSubmitMatchScoreData = {
    id: string;
    requestBody: MatchScoreSubmit;
};

export type FifotecaSubmitMatchScoreResponse = (FifotecaMatchPublic);

export type FifotecaConfirmMatchResultData = {
    id: string;
};

export type FifotecaConfirmMatchResultResponse = (FifotecaMatchPublic);

export type FifotecaListMatchesResponse = (MatchesPublic);

export type FifotecaGetMatchData = {
    id: string;
};

export type FifotecaGetMatchResponse = (FifotecaMatchDetail);

export type FifotecaGetPlayerProfileResponse = (FifotecaPlayerPublic);

export type FifotecaCreateOrGetPlayerProfileResponse = (FifotecaPlayerPublic);

export type FifotecaCreateRoomData = {
    ruleset?: string;
};

export type FifotecaCreateRoomResponse = (FifotecaRoomPublic);

export type FifotecaJoinRoomData = {
    code: string;
};

export type FifotecaJoinRoomResponse = (FifotecaRoomPublic);

export type FifotecaGetRoomData = {
    code: string;
};

export type FifotecaGetRoomResponse = (FifotecaRoomWithStatesPublic);

export type FifotecaReadTeamsData = {
    /**
     * Filter by league ID
     */
    leagueId?: (string | null);
    /**
     * Maximum overall rating
     */
    maxRating?: (number | null);
    /**
     * Minimum overall rating
     */
    minRating?: (number | null);
};

export type FifotecaReadTeamsResponse = (Array<FifaTeamPublic>);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);