"""add fifoteca tables

Revision ID: 3a1295a2b5eb
Revises: fe56fa70289e
Create Date: 2026-02-20 12:36:23.501147

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "3a1295a2b5eb"
down_revision = "fe56fa70289e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fifaleague",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "fifateam",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("league_id", sa.Uuid(), nullable=False),
        sa.Column("attack_rating", sa.Integer(), nullable=False),
        sa.Column("midfield_rating", sa.Integer(), nullable=False),
        sa.Column("defense_rating", sa.Integer(), nullable=False),
        sa.Column("overall_rating", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["league_id"], ["fifaleague.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fifotecaplayer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_wins", sa.Integer(), nullable=False),
        sa.Column("total_losses", sa.Integer(), nullable=False),
        sa.Column("total_draws", sa.Integer(), nullable=False),
        sa.Column("has_protection", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "fifotecaroom",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
        sa.Column("ruleset", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("player1_id", sa.Uuid(), nullable=False),
        sa.Column("player2_id", sa.Uuid(), nullable=True),
        sa.Column("current_turn_player_id", sa.Uuid(), nullable=True),
        sa.Column("first_player_id", sa.Uuid(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("mutual_superspin_proposer_id", sa.Uuid(), nullable=True),
        sa.Column("mutual_superspin_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_turn_player_id"],
            ["fifotecaplayer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_player_id"],
            ["fifotecaplayer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player1_id"],
            ["fifotecaplayer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player2_id"],
            ["fifotecaplayer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fifotecaroom_code"), "fifotecaroom", ["code"], unique=True)
    op.create_table(
        "fifotecamatch",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("player1_id", sa.Uuid(), nullable=False),
        sa.Column("player2_id", sa.Uuid(), nullable=False),
        sa.Column("player1_team_id", sa.Uuid(), nullable=False),
        sa.Column("player2_team_id", sa.Uuid(), nullable=False),
        sa.Column("player1_score", sa.Integer(), nullable=True),
        sa.Column("player2_score", sa.Integer(), nullable=True),
        sa.Column("rating_difference", sa.Integer(), nullable=False),
        sa.Column("protection_awarded_to_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_by_id", sa.Uuid(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["player1_id"],
            ["fifotecaplayer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player1_team_id"],
            ["fifateam.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player2_id"],
            ["fifotecaplayer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player2_team_id"],
            ["fifateam.id"],
        ),
        sa.ForeignKeyConstraint(
            ["protection_awarded_to_id"],
            ["fifotecaplayer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["fifotecaroom.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["fifotecaplayer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fifotecaplayerstate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("league_spins_remaining", sa.Integer(), nullable=False),
        sa.Column("team_spins_remaining", sa.Integer(), nullable=False),
        sa.Column("current_league_id", sa.Uuid(), nullable=True),
        sa.Column("current_team_id", sa.Uuid(), nullable=True),
        sa.Column("league_locked", sa.Boolean(), nullable=False),
        sa.Column("team_locked", sa.Boolean(), nullable=False),
        sa.Column("has_superspin", sa.Boolean(), nullable=False),
        sa.Column("superspin_used", sa.Boolean(), nullable=False),
        sa.Column("has_parity_spin", sa.Boolean(), nullable=False),
        sa.Column("parity_spin_used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_league_id"],
            ["fifaleague.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_team_id"],
            ["fifateam.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["fifotecaplayer.id"],
        ),
        sa.ForeignKeyConstraint(["room_id"], ["fifotecaroom.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fifotecaplayerstate")
    op.drop_table("fifotecamatch")
    op.drop_index(op.f("ix_fifotecaroom_code"), table_name="fifotecaroom")
    op.drop_table("fifotecaroom")
    op.drop_table("fifotecaplayer")
    op.drop_table("fifateam")
    op.drop_table("fifaleague")
    # ### end Alembic commands ###
