/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutFifotecaIndexRouteImport } from './routes/_layout/fifoteca/index'
import { Route as LayoutFifotecaHistoryRouteImport } from './routes/_layout/fifoteca/history'
import { Route as LayoutFifotecaMatchMatchIdRouteImport } from './routes/_layout/fifoteca/match.$matchId'
import { Route as LayoutFifotecaLobbyRoomCodeRouteImport } from './routes/_layout/fifoteca/lobby.$roomCode'
import { Route as LayoutFifotecaGameRoomCodeRouteImport } from './routes/_layout/fifoteca/game.$roomCode'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFifotecaIndexRoute = LayoutFifotecaIndexRouteImport.update({
  id: '/fifoteca/',
  path: '/fifoteca/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFifotecaHistoryRoute = LayoutFifotecaHistoryRouteImport.update({
  id: '/fifoteca/history',
  path: '/fifoteca/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFifotecaMatchMatchIdRoute =
  LayoutFifotecaMatchMatchIdRouteImport.update({
    id: '/fifoteca/match/$matchId',
    path: '/fifoteca/match/$matchId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFifotecaLobbyRoomCodeRoute =
  LayoutFifotecaLobbyRoomCodeRouteImport.update({
    id: '/fifoteca/lobby/$roomCode',
    path: '/fifoteca/lobby/$roomCode',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFifotecaGameRoomCodeRoute =
  LayoutFifotecaGameRoomCodeRouteImport.update({
    id: '/fifoteca/game/$roomCode',
    path: '/fifoteca/game/$roomCode',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/fifoteca/history': typeof LayoutFifotecaHistoryRoute
  '/fifoteca/': typeof LayoutFifotecaIndexRoute
  '/fifoteca/game/$roomCode': typeof LayoutFifotecaGameRoomCodeRoute
  '/fifoteca/lobby/$roomCode': typeof LayoutFifotecaLobbyRoomCodeRoute
  '/fifoteca/match/$matchId': typeof LayoutFifotecaMatchMatchIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/fifoteca/history': typeof LayoutFifotecaHistoryRoute
  '/fifoteca': typeof LayoutFifotecaIndexRoute
  '/fifoteca/game/$roomCode': typeof LayoutFifotecaGameRoomCodeRoute
  '/fifoteca/lobby/$roomCode': typeof LayoutFifotecaLobbyRoomCodeRoute
  '/fifoteca/match/$matchId': typeof LayoutFifotecaMatchMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/fifoteca/history': typeof LayoutFifotecaHistoryRoute
  '/_layout/fifoteca/': typeof LayoutFifotecaIndexRoute
  '/_layout/fifoteca/game/$roomCode': typeof LayoutFifotecaGameRoomCodeRoute
  '/_layout/fifoteca/lobby/$roomCode': typeof LayoutFifotecaLobbyRoomCodeRoute
  '/_layout/fifoteca/match/$matchId': typeof LayoutFifotecaMatchMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/fifoteca/history'
    | '/fifoteca/'
    | '/fifoteca/game/$roomCode'
    | '/fifoteca/lobby/$roomCode'
    | '/fifoteca/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/fifoteca/history'
    | '/fifoteca'
    | '/fifoteca/game/$roomCode'
    | '/fifoteca/lobby/$roomCode'
    | '/fifoteca/match/$matchId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/fifoteca/history'
    | '/_layout/fifoteca/'
    | '/_layout/fifoteca/game/$roomCode'
    | '/_layout/fifoteca/lobby/$roomCode'
    | '/_layout/fifoteca/match/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fifoteca/': {
      id: '/_layout/fifoteca/'
      path: '/fifoteca'
      fullPath: '/fifoteca/'
      preLoaderRoute: typeof LayoutFifotecaIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fifoteca/history': {
      id: '/_layout/fifoteca/history'
      path: '/fifoteca/history'
      fullPath: '/fifoteca/history'
      preLoaderRoute: typeof LayoutFifotecaHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fifoteca/match/$matchId': {
      id: '/_layout/fifoteca/match/$matchId'
      path: '/fifoteca/match/$matchId'
      fullPath: '/fifoteca/match/$matchId'
      preLoaderRoute: typeof LayoutFifotecaMatchMatchIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fifoteca/lobby/$roomCode': {
      id: '/_layout/fifoteca/lobby/$roomCode'
      path: '/fifoteca/lobby/$roomCode'
      fullPath: '/fifoteca/lobby/$roomCode'
      preLoaderRoute: typeof LayoutFifotecaLobbyRoomCodeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fifoteca/game/$roomCode': {
      id: '/_layout/fifoteca/game/$roomCode'
      path: '/fifoteca/game/$roomCode'
      fullPath: '/fifoteca/game/$roomCode'
      preLoaderRoute: typeof LayoutFifotecaGameRoomCodeRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFifotecaHistoryRoute: typeof LayoutFifotecaHistoryRoute
  LayoutFifotecaIndexRoute: typeof LayoutFifotecaIndexRoute
  LayoutFifotecaGameRoomCodeRoute: typeof LayoutFifotecaGameRoomCodeRoute
  LayoutFifotecaLobbyRoomCodeRoute: typeof LayoutFifotecaLobbyRoomCodeRoute
  LayoutFifotecaMatchMatchIdRoute: typeof LayoutFifotecaMatchMatchIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFifotecaHistoryRoute: LayoutFifotecaHistoryRoute,
  LayoutFifotecaIndexRoute: LayoutFifotecaIndexRoute,
  LayoutFifotecaGameRoomCodeRoute: LayoutFifotecaGameRoomCodeRoute,
  LayoutFifotecaLobbyRoomCodeRoute: LayoutFifotecaLobbyRoomCodeRoute,
  LayoutFifotecaMatchMatchIdRoute: LayoutFifotecaMatchMatchIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
